version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ' '
    template = '{{ .UserName }}'
    foreground = '#E64747'
    background = '#29315A'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Path }}'
    foreground = '#3EC669'
    background = '#29315A'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ .HEAD }}'
    foreground = '#43CCEA'
    background = '#29315A'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      branch_icon = ''

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
    foreground = '#E4F34A'
    background = '#29315A'
    type = 'python'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = '#7FD5EA'
    background = '#29315A'
    type = 'go'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'
    foreground = '#42E66C'
    background = '#29315A'
    type = 'node'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = '#E64747'
    background = '#29315A'
    type = 'ruby'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = '#E64747'
    background = '#29315A'
    type = 'java'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#9B6BDF'
    background = '#29315A'
    type = 'julia'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}'
    foreground = '#9B6BDF'
    background = '#29315A'
    type = 'battery'
    style = 'diamond'
    foreground_templates = ['{{if eq "Charging" .State.String}}#40c4ff{{end}}', '{{if eq "Discharging" .State.String}}#ff5722{{end}}', '{{if eq "Full" .State.String}}#4caf50{{end}}']

    [blocks.segments.properties]
      charged_icon = ' '
      charging_icon = '⇡ '
      discharging_icon = '⇣ '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ' '
    template = '{{ .FormattedMs }}'
    foreground = '#AEA4BF'
    background = '#29315A'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'austin'
      threshold = 150.0

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '❯'
    foreground = '#7FD5EA'
    background = '#29315A'
    type = 'text'
    style = 'diamond'
